this one should work

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,18 +9,23 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
-      - name: deploy
+      - name: Deploy
         run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
           chmod 600 private_key
           eval $(ssh-agent -s)
-          ssh-add private_key
+          ssh-add private_key || { echo "ssh-add failed with exit code $?"; exit 1; }
           mkdir -p ~/.ssh
-          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+          chmod 700 ~/.ssh
+          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || { echo "ssh-keyscan failed with exit code $?"; exit 1; }
           echo "Deploying to EC2"
-          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
+          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
             mkdir -p ${{ secrets.TARGET_DIR }} &&
             cd ${{ secrets.TARGET_DIR }} &&
-            git pull origin master
+            if [ -d .git ]; then
+              git pull origin master;
+            else
+              rm -rf * &&
+              git clone https://github.com/austenstrine/austenstrine_portfolio.git .;
+            fi
           "
